[project]
name = "uv-pyo3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["altair>=5.4.1", "polars>=1.8.2"]

[tool.uv]
dev-dependencies = ["pytest>=8.3.3"]
